### ISSUE TITLE
Missing Permissions Error when added to a new guild. (Even with admin perms)

### ISSUE THREAD

**Issue by seasaltsaige** [CreeperPlanet26/Slash-Commands#1]
https://github.com/CreeperPlanet26/Slash-Commands/blob/7534f9840b8d782ff6d5294da2a8df21fcfcedbf/src/SlashCommands/SlashCommand/InitCommands.ts#L21
```
Slash-Commands\node_modules\discord.js\src\rest\RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^
DiscordAPIError: Missing Access
    at RequestHandler.execute (C:\Users\orion\Documents\npm-packages\Slash-Commands\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at RequestHandler.push (C:\Users\orion\Documents\npm-packages\Slash-Commands\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at RestHandler.get_commands (C:\Users\orion\Documents\npm-packages\Slash-Commands\src\SlashCommands\RestHandler\RestHandler.ts:21:12)
    at async Promise.all (index 3)
    at Object.initCommands (C:\Users\orion\Documents\npm-packages\Slash-Commands\src\SlashCommands\SlashCommand\InitCommands.ts:20:34)
    at SlashCommands._init (C:\Users\orion\Documents\npm-packages\Slash-Commands\src\SlashCommands\SlashCommands.ts:16:5)
```

**Comment by seasaltsaige** [comment]
It might have something to do with there being no slash commands? But then the other old guilds that it was already in just return an empty array... Only the newest guild returns undefined.

```js
[
  [], // Code Camp
  [], // CD Test Server
  [
    {
      id: '831971563741773825',
      application_id: '776538408780038144',
      name: 'somecommand',
      description: 'Some test guild Command',
      version: '831973817953419295',
      default_permission: true,
      guild_id: '797927305456254997'
    }
  ], // Dev
  undefined // Newest Server
]
```

**Comment by seasaltsaige** [comment]
Global Slash Commands are also not appearing in the newest server

**Comment by seasaltsaige** [comment]
Same Error when posting a guild specific command to the new server

**Comment by sohank1** [comment]
> Global Slash Commands are also not appearing in the newest server

Yeah they can take hours, we can't really do anything it's a discord api thing

**Comment by sohank1** [comment]
I'm not really sure why this error is happening

**Comment by sohank1** [comment]
Maybe after the few hours it stops giving it?

**Comment by seasaltsaige** [comment]
Not as far as I can tell, pretty sure its the daily limit, or something related
